### ISSUE TITLE
gallery.ts:158: prevent initialising default

### ISSUE THREAD

**Issue by 0pdd** [aaronmyatt/gridstack-gallery#3]
The puzzle `1-162deada` from #1 has to be resolved: 

https://github.com/aaronmyatt/gridstack-gallery/blob/f2ae4c4e88170dae4548aac208b88827c1b73181/src/gallery.ts#L158-L158

The puzzle was created by @aaronmyatt on 04-Aug-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by aaronmyatt** [comment]
this is shooting me in the foot when trying to render a grid late because an error is thrown if the default `.gsg` selector is missing.

Need to consider whether to add a delay to initialising if the selector is not immediately discovered.

**Comment by aaronmyatt** [comment]
In the end, given my experience with other libraries, like PubSub.js, perhaps it makes more sense not to execute immediately, but instead make the GridStackGallery initialisation method globally available (on the Window object in this case). This is how PubSub.js works itself, though that's because there's nothing for it to render to the screen 🤷
